### ISSUE TITLE
Failing to run because of ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by SilentImp** [entropitor/dotenv-cli#13]
I am trying to run it in the same directory where .env are.

```
$ node -v
v11.9.0

$ dotenv
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:414:3)
    at Object.spawn (child_process.js:553:16)
    at spawn (/Users/silentimp/.nvm/versions/node/v11.9.0/lib/node_modules/dotenv-cli/node_modules/cross-spawn/index.js:17:18)
    at Object.<anonymous> (/Users/silentimp/.nvm/versions/node/v11.9.0/lib/node_modules/dotenv-cli/cli.js:26:1)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
```

but it work with --p

```
$ dotenv -p REACT_APP_LOCALE
it
```

What has gone wrong?

**Comment by SilentImp** [comment]
On 10 and 8 node version it also fails this way.
mac os x 10.14

**Comment by entropitor** [comment]
You need to call a command e.g. `dotenv -- npm run test`
