### ISSUE TITLE
"file" argument must be a non-empty string'

### ISSUE THREAD

**Issue by naguibihab** [entropitor/dotenv-cli#19]
I am trying to run dotenv on my local project which has a `.env` file in the root but I'm getting this error

```
$ dotenv -e .env
child_process.js:389
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:389:11)
    at Object.exports.spawn (child_process.js:502:38)
    at spawn (/Users/localuser/.config/yarn/global/node_modules/dotenv-cli/node_modules/cross-spawn/index.js:17:18)
    at Object.<anonymous> (/Users/localuser/.config/yarn/global/node_modules/dotenv-cli/cli.js:27:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
```

**Comment by entropitor** [comment]
You need to pass a process that you want to run

e.g. `dotenv -e .env node index.js`
