### ISSUE TITLE
npm ERR! could not determine executable to run

### ISSUE THREAD

**Issue by ctsstc** [entropitor/dotenv-cli#96]
When I try to run `npx dotenv` I get the following error: 

```
> npx dotenv
npm ERR! could not determine executable to run
```

## Versions

```
> node -v
v18.16.0

> npm -v
9.5.1
```

## Full Debug Log
```
0 verbose cli /Users/coder/.asdf/installs/nodejs/18.16.0/bin/node /Users/coder/.asdf/installs/nodejs/18.16.0/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@9.5.1
2 info using node@v18.16.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/coder/.asdf/installs/nodejs/18.16.0/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 0ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/coder/projects/project-name/ssr/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/coder/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/Users/coder/.asdf/installs/nodejs/18.16.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 4ms
17 timing npm:load:configload Completed in 4ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm exec dotenv
21 verbose argv "exec" "--" "dotenv"
22 timing npm:load:setTitle Completed in 6ms
23 timing config:load:flatten Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/Users/coder/.npm/_logs/2023-09-05T21_57_41_214Z-
26 verbose logfile /Users/coder/.npm/_logs/2023-09-05T21_57_41_214Z-debug-0.log
27 timing npm:load:logFile Completed in 3ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 14ms
31 silly logfile start cleaning logs, removing 2 files
32 silly logfile done cleaning log files
33 timing arborist:ctor Completed in 0ms
34 timing arborist:ctor Completed in 0ms
35 timing command:exec Completed in 211ms
36 verbose stack Error: could not determine executable to run
36 verbose stack     at getBinFromManifest (/Users/coder/.asdf/installs/nodejs/18.16.0/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
36 verbose stack     at exec (/Users/coder/.asdf/installs/nodejs/18.16.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:185:15)
36 verbose stack     at async module.exports (/Users/coder/.asdf/installs/nodejs/18.16.0/lib/node_modules/npm/lib/cli.js:134:5)
37 verbose pkgid dotenv@16.3.1
38 verbose cwd /Users/coder/projects/project-name/ssr
39 verbose Darwin 22.3.0
40 verbose node v18.16.0
41 verbose npm  v9.5.1
42 error could not determine executable to run
43 verbose exit 1
44 timing npm Completed in 234ms
45 verbose code 1
46 error A complete log of this run can be found in:
46 error     /Users/coder/.npm/_logs/2023-09-05T21_57_41_214Z-debug-0.log
```

**Comment by entropitor** [comment]
I don't know `npx` by hard but I think you have to run `npx dotenv-cli` given the package is named that way? AFAICT from running it in a docker image, that seems to work while `npx dotenv` does fail indeed.
